In [826]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import MinMaxScaler




pd.set_option('display.max_columns', None)

In [788]:
df=pd.read_csv('data_rev3.csv')
df.shape

/var/folders/0h/k469m22d4nlb8wt5k446w_z40000gn/T/ipykernel_35021/2391098834.py:1: DtypeWarning: Columns (5,11,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('data_rev3.csv')

(81315, 33)

In [789]:
df.isnull().sum()

order_day                    0
accept                       0
tos_flg                  71569
disconotice_flg              0
oam_activelogin_cnt          0
term_length                  0
called_numcalls_cnt          0
latefee_flg                  0
dwelling_type_cd             0
curr_usage                8349
product_type_cd              0
pool                     79626
automatic_payment_flg        0
weblog_flg                   0
risk_level               34733
deposit_onhand_amt       76315
ebill_enroll_flag            0
called_flg                   0
oam_flg                      0
sap_productname            208
numweblog_cnt                0
disconnects_flg              0
load_profile                 0
city                         0
zipcode                      0
home_value               60677
county                       0
tdsp                         0
dma                          0
ev_driver                    0
segment                      0
customer_id                  0
meter_id                     0
dtype: int64

In [790]:
df.columns

Index(['order_day', 'accept', 'tos_flg', 'disconotice_flg',
       'oam_activelogin_cnt', 'term_length', 'called_numcalls_cnt',
       'latefee_flg', 'dwelling_type_cd', 'curr_usage', 'product_type_cd',
       'pool', 'automatic_payment_flg', 'weblog_flg', 'risk_level',
       'deposit_onhand_amt', 'ebill_enroll_flag', 'called_flg', 'oam_flg',
       'sap_productname', 'numweblog_cnt', 'disconnects_flg', 'load_profile',
       'city', 'zipcode', 'home_value', 'county', 'tdsp', 'dma', 'ev_driver',
       'segment', 'customer_id', 'meter_id'],
      dtype='object')

In [791]:
df.order_day=pd.to_datetime(df.order_day,format='%d/%m/%Y')

In [792]:
df.head()

,order_day,accept,tos_flg,disconotice_flg,oam_activelogin_cnt,term_length,called_numcalls_cnt,latefee_flg,dwelling_type_cd,curr_usage,product_type_cd,pool,automatic_payment_flg,weblog_flg,risk_level,deposit_onhand_amt,ebill_enroll_flag,called_flg,oam_flg,sap_productname,numweblog_cnt,disconnects_flg,load_profile,city,zipcode,home_value,county,tdsp,dma,ev_driver,segment,customer_id,meter_id
0,2017-01-01,0,NaN,N,0,0,0,N,M,188.0,MTM,NaN,N,N,M,NaN,Y,N,Y,Reliant Flex plan,0,N,R2,DALLAS,752405170,NaN,DALLAS,ONC,DALLAS-FT. WORTH,N,6,55843,11745
1,2017-01-01,0,NaN,N,0,19,0,N,M,167.0,TERM,NaN,N,N,H,NaN,N,N,N,Reliant Easy Look 19 plan,0,N,R1,HOUSTON,770649432,NaN,HARRIS,CNP,HOUSTON,N,5,17325,25319
2,2017-01-01,0,NaN,N,0,48,0,N,M,188.0,TERM,NaN,N,N,NaN,NaN,N,N,N,Reliant Easy Look 48 plan,0,N,R1,HOUSTON,77007,NaN,HARRIS,CNP,HOUSTON,N,11,20004,23202
3,2017-01-02,0,NaN,N,0,9,1,N,M,135.0,TERM,NaN,N,N,NaN,NaN,Y,Y,Y,Reliant Secure 9 plan,0,N,R2,HOUSTON,770822427,NaN,HARRIS,CNP,HOUSTON,N,11,55635,11475
4,2017-01-02,1,NaN,N,0,12,0,N,S,617.0,TERM,NaN,N,N,L,NaN,N,N,Y,Reliant Secure 12 plan,0,N,R1,DALLAS,752086271,NaN,DALLAS,ONC,DALLAS-FT. WORTH,N,6,49599,38365

In [793]:
# df['ID'] =df.customer_id.astype(str) + '_' + df['order_day'].astype(str)

In [794]:
# df=df.set_index('ID')

In [795]:
df.head()

,order_day,accept,tos_flg,disconotice_flg,oam_activelogin_cnt,term_length,called_numcalls_cnt,latefee_flg,dwelling_type_cd,curr_usage,product_type_cd,pool,automatic_payment_flg,weblog_flg,risk_level,deposit_onhand_amt,ebill_enroll_flag,called_flg,oam_flg,sap_productname,numweblog_cnt,disconnects_flg,load_profile,city,zipcode,home_value,county,tdsp,dma,ev_driver,segment,customer_id,meter_id
0,2017-01-01,0,NaN,N,0,0,0,N,M,188.0,MTM,NaN,N,N,M,NaN,Y,N,Y,Reliant Flex plan,0,N,R2,DALLAS,752405170,NaN,DALLAS,ONC,DALLAS-FT. WORTH,N,6,55843,11745
1,2017-01-01,0,NaN,N,0,19,0,N,M,167.0,TERM,NaN,N,N,H,NaN,N,N,N,Reliant Easy Look 19 plan,0,N,R1,HOUSTON,770649432,NaN,HARRIS,CNP,HOUSTON,N,5,17325,25319
2,2017-01-01,0,NaN,N,0,48,0,N,M,188.0,TERM,NaN,N,N,NaN,NaN,N,N,N,Reliant Easy Look 48 plan,0,N,R1,HOUSTON,77007,NaN,HARRIS,CNP,HOUSTON,N,11,20004,23202
3,2017-01-02,0,NaN,N,0,9,1,N,M,135.0,TERM,NaN,N,N,NaN,NaN,Y,Y,Y,Reliant Secure 9 plan,0,N,R2,HOUSTON,770822427,NaN,HARRIS,CNP,HOUSTON,N,11,55635,11475
4,2017-01-02,1,NaN,N,0,12,0,N,S,617.0,TERM,NaN,N,N,L,NaN,N,N,Y,Reliant Secure 12 plan,0,N,R1,DALLAS,752086271,NaN,DALLAS,ONC,DALLAS-FT. WORTH,N,6,49599,38365

In [796]:
df.risk_level.mode().values[0]

'L'

In [797]:
## Drop home_value & Pool
## Frency encoding sap_prdocutname
## city, zipcoe, county,dma -- top 3 + others

## Sometimes a hybrid approach can be useful. For example, you might treat year as a numeric feature to capture linear trends over time, while treating day of the week and month as categorical to capture their cyclical nature.

## Date Features
df['OrderYear']=df.order_day.dt.year
df['OrderMonth']=df.order_day.dt.month
df['OrderDay']=df.order_day.dt.day
df['OrderDayOfYear']=df.order_day.dt.dayofyear
df['OrderDayOfWeek']=df.order_day.dt.dayofweek
df['IsWeekend'] = df['OrderDayOfWeek'].apply(lambda x: 1 if x >= 5 else 0)


## tos_flg
df.loc[df.tos_flg.isnull(),'tos_flg']='N'

## term_length
df['term_length'] = pd.to_numeric(df['term_length'], errors='coerce').fillna(0).astype(int)

## curr_usage
df['curr_usage'].fillna(0,inplace=True)

## risk_level (filling missing values by mode)
df.risk_level.fillna(df.risk_level.mode().values[0],inplace=True)

## sap_productname (filling missing values by mode)
df.sap_productname.fillna(df.sap_productname.mode().values[0],inplace=True)


## deposit_onhand_amt
df['deposit_onhand_amt'].fillna(0,inplace=True)

## Convert features to correct datatype
df['zipcode']=df['zipcode'].apply(str)
df['segment']=df['segment'].apply(str)
df['OrderMonth']=df['OrderMonth'].apply(str)
df['OrderDayOfWeek']=df['OrderDayOfWeek'].apply(str)

In [798]:
df.head()

,order_day,accept,tos_flg,disconotice_flg,oam_activelogin_cnt,term_length,called_numcalls_cnt,latefee_flg,dwelling_type_cd,curr_usage,product_type_cd,pool,automatic_payment_flg,weblog_flg,risk_level,deposit_onhand_amt,ebill_enroll_flag,called_flg,oam_flg,sap_productname,numweblog_cnt,disconnects_flg,load_profile,city,zipcode,home_value,county,tdsp,dma,ev_driver,segment,customer_id,meter_id,OrderYear,OrderMonth,OrderDay,OrderDayOfYear,OrderDayOfWeek,IsWeekend
0,2017-01-01,0,N,N,0,0,0,N,M,188.0,MTM,NaN,N,N,M,0.0,Y,N,Y,Reliant Flex plan,0,N,R2,DALLAS,752405170,NaN,DALLAS,ONC,DALLAS-FT. WORTH,N,6,55843,11745,2017,1,1,1,6,1
1,2017-01-01,0,N,N,0,19,0,N,M,167.0,TERM,NaN,N,N,H,0.0,N,N,N,Reliant Easy Look 19 plan,0,N,R1,HOUSTON,770649432,NaN,HARRIS,CNP,HOUSTON,N,5,17325,25319,2017,1,1,1,6,1
2,2017-01-01,0,N,N,0,48,0,N,M,188.0,TERM,NaN,N,N,L,0.0,N,N,N,Reliant Easy Look 48 plan,0,N,R1,HOUSTON,77007,NaN,HARRIS,CNP,HOUSTON,N,11,20004,23202,2017,1,1,1,6,1
3,2017-01-02,0,N,N,0,9,1,N,M,135.0,TERM,NaN,N,N,L,0.0,Y,Y,Y,Reliant Secure 9 plan,0,N,R2,HOUSTON,770822427,NaN,HARRIS,CNP,HOUSTON,N,11,55635,11475,2017,1,2,2,0,0
4,2017-01-02,1,N,N,0,12,0,N,S,617.0,TERM,NaN,N,N,L,0.0,N,N,Y,Reliant Secure 12 plan,0,N,R1,DALLAS,752086271,NaN,DALLAS,ONC,DALLAS-FT. WORTH,N,6,49599,38365,2017,1,2,2,0,0

In [799]:
df.dtypes

order_day                datetime64[ns]
accept                            int64
tos_flg                          object
disconotice_flg                  object
oam_activelogin_cnt               int64
term_length                       int64
called_numcalls_cnt               int64
latefee_flg                      object
dwelling_type_cd                 object
curr_usage                      float64
product_type_cd                  object
pool                             object
automatic_payment_flg            object
weblog_flg                       object
risk_level                       object
deposit_onhand_amt              float64
ebill_enroll_flag                object
called_flg                       object
oam_flg                          object
sap_productname                  object
numweblog_cnt                     int64
disconnects_flg                  object
load_profile                     object
city                             object
zipcode                          object
home_value                      float64
county                           object
tdsp                             object
dma                              object
ev_driver                        object
segment                          object
customer_id                       int64
meter_id                          int64
OrderYear                         int64
OrderMonth                       object
OrderDay                          int64
OrderDayOfYear                    int64
OrderDayOfWeek                   object
IsWeekend                         int64
dtype: object

In [800]:
ignore_cols=['accept','pool','home_value','meter_id','customer_id','order_day']
features=[i for i in df.columns if i not in ignore_cols]
print(features)

X=df[features]
y=df['accept']

['tos_flg', 'disconotice_flg', 'oam_activelogin_cnt', 'term_length', 'called_numcalls_cnt', 'latefee_flg', 'dwelling_type_cd', 'curr_usage', 'product_type_cd', 'automatic_payment_flg', 'weblog_flg', 'risk_level', 'deposit_onhand_amt', 'ebill_enroll_flag', 'called_flg', 'oam_flg', 'sap_productname', 'numweblog_cnt', 'disconnects_flg', 'load_profile', 'city', 'zipcode', 'county', 'tdsp', 'dma', 'ev_driver', 'segment', 'OrderYear', 'OrderMonth', 'OrderDay', 'OrderDayOfYear', 'OrderDayOfWeek', 'IsWeekend']

In [801]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,stratify=y,shuffle=True, random_state=7)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2,stratify=y_train,shuffle=True, random_state=7) # 0.25 x 0.8 = 0.2

In [802]:
print('X_train Shape:{}--y_train Shape:{}'.format(X_train.shape,y_train.shape))
print('X_val Shape:{}--y_val Shape:{}'.format(X_val.shape,y_val.shape))
print('X_test Shape:{}--y_test Shape:{}'.format(X_test.shape,y_test.shape))

X_train Shape:(52041, 33)--y_train Shape:(52041,)
X_val Shape:(13011, 33)--y_val Shape:(13011,)
X_test Shape:(16263, 33)--y_test Shape:(16263,)

In [803]:
y_train.value_counts(normalize=True)

0    0.831229
1    0.168771
Name: accept, dtype: float64

In [804]:
y_val.value_counts(normalize=True)

0    0.83122
1    0.16878
Name: accept, dtype: float64

In [805]:
y_test.value_counts(normalize=True)

0    0.831212
1    0.168788
Name: accept, dtype: float64

In [806]:
# df['ID']=df['customer_id'].apply(lambda x : str(x)) +'_'+df['meter_id'].apply(lambda x : str(x))+'_'+ df['order_day'].apply(lambda x : str(x))

In [807]:
X_test

,tos_flg,disconotice_flg,oam_activelogin_cnt,term_length,called_numcalls_cnt,latefee_flg,dwelling_type_cd,curr_usage,product_type_cd,automatic_payment_flg,weblog_flg,risk_level,deposit_onhand_amt,ebill_enroll_flag,called_flg,oam_flg,sap_productname,numweblog_cnt,disconnects_flg,load_profile,city,zipcode,county,tdsp,dma,ev_driver,segment,OrderYear,OrderMonth,OrderDay,OrderDayOfYear,OrderDayOfWeek,IsWeekend
22630,N,N,0,12,0,N,M,472.0,TERM,Y,N,L,0.0,Y,N,Y,Reliant Secure 12 100 Wind plan,0,N,R1,HOUSTON,770244078,HARRIS,CNP,HOUSTON,N,11,2017,8,25,237,4,0
17439,N,N,0,12,0,N,M,0.0,TERM,N,N,L,0.0,N,N,N,Reliant Secure 12 plan,0,N,R2,HOUSTON,770991981,HARRIS,CNP,HOUSTON,N,3,2017,5,17,137,2,0
8440,N,N,0,12,1,N,S,0.0,TERM,N,N,L,0.0,N,Y,N,Reliant Secure 12 plan,0,N,R1,HARKER HEIGHTS,765482219,BELL,ONC,WACO-TEMPLE-BRYAN,N,6,2017,1,19,19,3,0
20339,N,N,0,12,0,N,M,0.0,TERM,N,N,L,0.0,Y,N,N,Reliant Flex plan,0,N,R2,HOUSTON,770304719,HARRIS,CNP,HOUSTON,N,11,2017,8,21,233,0,0
996,N,N,0,12,0,N,S,1160.0,TERM,N,N,L,0.0,N,N,N,Reliant Builder Power Plus 12 plan,0,N,R1,HOUSTON,77018,HARRIS,CNP,HOUSTON,N,9,2017,1,10,10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51682,N,N,0,12,0,N,S,1083.0,TERM,Y,N,M,0.0,Y,N,Y,Reliant Secure Advantage 12 plan,0,N,R1,WICHITA FALLS,763024313,WICHITA,ONC,WICHITA FALLS & LAWTON,N,10,2018,12,20,354,3,0
60548,N,N,0,18,0,N,M,236.0,TERM,Y,N,L,0.0,Y,N,Y,Reliant Truly Free Weekends 18 plan,0,N,R1,HOUSTON,770141223,HARRIS,CNP,HOUSTON,N,3,2019,1,4,4,4,0
59795,N,N,0,0,0,Y,M,731.0,MTM,N,Y,L,0.0,Y,N,Y,Reliant Flex plan,5,N,R1,TYLER,757033747,SMITH,ONC,TYLER-LONGVIEW(LFKN&NCGD),N,3,2019,1,4,4,4,0
79980,N,N,0,0,0,N,S,963.0,MTM,Y,N,M,0.0,Y,N,Y,Reliant Flex plan,0,N,R1,PEARLAND,77584,BRAZORIA,CNP,HOUSTON,N,11,2020,11,30,335,0,0
44470,N,N,0,60,1,Y,S,1160.0,TERM,N,N,M,0.0,N,Y,N,Reliant Plain and Simple 60 plan,0,N,R2,FORT WORTH,761112324,TARRANT,ONC,DALLAS-FT. WORTH,N,4,2018,2,14,45,2,0

In [808]:
X_train.dtypes.unique()

array([dtype('O'), dtype('int64'), dtype('float64')], dtype=object)

## Feature Engineering

- sap_productname : Frequency or Count Encoding: Replace each category with its frequency (or count) in the dataset. 
- 'city', 'zipcode', 'county', dma : Only considering top 3 categories from these features and clubbing evrything else in 'other' category.

## sap_productname transfromation

In [809]:
sap_productname_frequency_map = X_train['sap_productname'].value_counts().to_dict()
# print(sap_productname_frequency_map)

In [810]:
# Save the mapping
with open('sap_productname_freq_map.json', 'w') as file:
    json.dump(sap_productname_frequency_map, file)

In [811]:
# Map frequencies to the categories in train, test, and validation sets
X_train['sap_productname'] = X_train['sap_productname'].map(sap_productname_frequency_map)
X_test['sap_productname'] = X_test['sap_productname'].map(sap_productname_frequency_map)
X_val['sap_productname'] = X_val['sap_productname'].map(sap_productname_frequency_map)

# Handling missing values if any category in test/val is not present in train
X_test['sap_productname'].fillna(0, inplace=True)
X_val['sap_productname'].fillna(0, inplace=True)


X_train['sap_productname'] = X_train['sap_productname'].astype(np.int64)
X_test['sap_productname'] = X_test['sap_productname'].astype(np.int64)
X_val['sap_productname'] = X_val['sap_productname'].astype(np.int64)

In [812]:
print('X_train Shape:{}--y_train Shape:{}'.format(X_train.shape,y_train.shape))
print('X_val Shape:{}--y_val Shape:{}'.format(X_val.shape,y_val.shape))
print('X_test Shape:{}--y_test Shape:{}'.format(X_test.shape,y_test.shape))

X_train Shape:(52041, 33)--y_train Shape:(52041,)
X_val Shape:(13011, 33)--y_val Shape:(13011,)
X_test Shape:(16263, 33)--y_test Shape:(16263,)

In [813]:
# Identifying numerical and categorical columns
num_cols = X_train.select_dtypes(include=['int64', 'float64']).columns

ctgy_cols = X_train.select_dtypes(include=['object']).columns
print('num Columns: {} \n\nctgy columns: {}'.format(num_cols,ctgy_cols))

num Columns: Index(['oam_activelogin_cnt', 'term_length', 'called_numcalls_cnt',
       'curr_usage', 'deposit_onhand_amt', 'sap_productname', 'numweblog_cnt',
       'OrderYear', 'OrderDay', 'OrderDayOfYear', 'IsWeekend'],
      dtype='object')

ctgy columns: Index(['tos_flg', 'disconotice_flg', 'latefee_flg', 'dwelling_type_cd',
       'product_type_cd', 'automatic_payment_flg', 'weblog_flg', 'risk_level',
       'ebill_enroll_flag', 'called_flg', 'oam_flg', 'disconnects_flg',
       'load_profile', 'city', 'zipcode', 'county', 'tdsp', 'dma', 'ev_driver',
       'segment', 'OrderMonth', 'OrderDayOfWeek'],
      dtype='object')

In [814]:
X_train.head()

,tos_flg,disconotice_flg,oam_activelogin_cnt,term_length,called_numcalls_cnt,latefee_flg,dwelling_type_cd,curr_usage,product_type_cd,automatic_payment_flg,weblog_flg,risk_level,deposit_onhand_amt,ebill_enroll_flag,called_flg,oam_flg,sap_productname,numweblog_cnt,disconnects_flg,load_profile,city,zipcode,county,tdsp,dma,ev_driver,segment,OrderYear,OrderMonth,OrderDay,OrderDayOfYear,OrderDayOfWeek,IsWeekend
14152,N,N,0,12,0,N,S,0.0,TERM,N,N,L,0.0,N,N,N,1467,0,N,R2,PASADENA,775052103,HARRIS,CNP,HOUSTON,N,6,2017,3,24,83,4,0
42976,N,N,0,12,1,N,M,0.0,TERM,N,N,M,0.0,N,Y,N,389,0,N,R1,RICHMOND,77406,FORT BEND,CNP,HOUSTON,N,12,2018,1,11,11,3,0
78273,N,N,0,0,0,N,S,550.0,MTM,Y,N,L,0.0,N,N,Y,1318,0,N,R1,SANTA FE,77510,GALVESTON,CNP,HOUSTON,N,4,2020,11,18,323,2,0
4847,N,N,0,16,0,N,S,2905.0,TERM,N,N,L,0.0,N,N,N,198,0,N,R2,HOUSTON,770723421,HARRIS,CNP,HOUSTON,N,3,2017,1,13,13,4,0
9228,N,N,0,36,0,N,M,58.0,TERM,N,N,L,0.0,N,N,N,386,0,N,R1,PEARLAND,77584,BRAZORIA,CNP,HOUSTON,N,11,2017,1,28,28,5,1

## Features with multiples categories only cosindering top 3 based on count remaining clubbed into'other' categiory

In [815]:
top_3_city = X_train['city'].value_counts().nlargest(3).index
top_3_zipcode = X_train['zipcode'].value_counts().nlargest(3).index
top_3_county = X_train['county'].value_counts().nlargest(3).index
top_3_dma = X_train['dma'].value_counts().nlargest(3).index

In [816]:
## city
X_train['city'] = X_train['city'].apply(lambda x: x if x in top_3_city else 'Other')
X_test['city'] = X_test['city'].apply(lambda x: x if x in top_3_city else 'Other')
X_val['city'] = X_val['city'].apply(lambda x: x if x in top_3_city else 'Other')

## zipcode
X_train['zipcode'] = X_train['zipcode'].apply(lambda x: x if x in top_3_zipcode else 'Other')
X_test['zipcode'] = X_test['zipcode'].apply(lambda x: x if x in top_3_zipcode else 'Other')
X_val['zipcode'] = X_val['zipcode'].apply(lambda x: x if x in top_3_zipcode else 'Other')

## county
X_train['county'] = X_train['county'].apply(lambda x: x if x in top_3_county else 'Other')
X_test['county'] = X_test['county'].apply(lambda x: x if x in top_3_county else 'Other')
X_val['county'] = X_val['county'].apply(lambda x: x if x in top_3_county else 'Other')

## dma
X_train['dma'] = X_train['dma'].apply(lambda x: x if x in top_3_dma else 'Other')
X_test['dma'] = X_test['dma'].apply(lambda x: x if x in top_3_dma else 'Other')
X_val['dma'] = X_val['dma'].apply(lambda x: x if x in top_3_dma else 'Other')

In [817]:
print('X_train Shape:{}--y_train Shape:{}'.format(X_train.shape,y_train.shape))
print('X_val Shape:{}--y_val Shape:{}'.format(X_val.shape,y_val.shape))
print('X_test Shape:{}--y_test Shape:{}'.format(X_test.shape,y_test.shape))

X_train Shape:(52041, 33)--y_train Shape:(52041,)
X_val Shape:(13011, 33)--y_val Shape:(13011,)
X_test Shape:(16263, 33)--y_test Shape:(16263,)

In [818]:
X_train.city.value_counts()

Other         30609
HOUSTON       15812
DALLAS         3490
FORT WORTH     2130
Name: city, dtype: int64

In [819]:
X_train.zipcode.value_counts()

Other    51601
77449      187
77469      128
77494      125
Name: zipcode, dtype: int64

In [820]:
top_categories = {
    'top_3_city': top_3_city.tolist(),
    'top_3_zipcode': top_3_zipcode.tolist(),
    'top_3_county': top_3_county.tolist(),
    'top_3_dma': top_3_dma.tolist()
}

## Saving for production
with open('top_categories.json', 'w') as file:
    json.dump(top_categories, file)

In [821]:
print('X_train Shape:{}--y_train Shape:{}'.format(X_train.shape,y_train.shape))
print('X_val Shape:{}--y_val Shape:{}'.format(X_val.shape,y_val.shape))
print('X_test Shape:{}--y_test Shape:{}'.format(X_test.shape,y_test.shape))

X_train Shape:(52041, 33)--y_train Shape:(52041,)
X_val Shape:(13011, 33)--y_val Shape:(13011,)
X_test Shape:(16263, 33)--y_test Shape:(16263,)

## Label Encoding --> One Hot Encoding for categorical features

In [822]:
# Function for Label Encoding multiple columns
def label_encode_multiple_columns(train, test, val, columns):
    encoders = {}
    for column in columns:
        # print('Issue column:{}'.format(column))
        le = LabelEncoder()
        # Fit on the train data and transform all datasets
        train[column] = le.fit_transform(train[column])
        test[column] = le.transform(test[column])
        val[column] = le.transform(val[column])
        encoders[column] = le
    return encoders

# Function for One-Hot Encoding multiple columns
def one_hot_encode_multiple_columns(train, test, val, columns):
    #ohe = OneHotEncoder(handle_unknown='ignore', sparse=False,drop='first')
    ohe = OneHotEncoder(handle_unknown='ignore',sparse_output=False)
    ohe.fit(train[columns])

    # Transform and create DataFrame from the encoded arrays
    def transform_and_create_df(data, columns):
        encoded = ohe.transform(data[columns])
        encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(), index=data.index)
        return data.drop(columns, axis=1).join(encoded_df)

    return transform_and_create_df(train, columns), transform_and_create_df(test, columns), transform_and_create_df(val, columns)

# Assuming X_train, X_test, X_val are your datasets
# label_columns = ['tos_flg', 'disconotice_flg']
# one_hot_columns = ['tos_flg', 'disconotice_flg']

label_columns = ctgy_cols
one_hot_columns = ctgy_cols
# Apply Label Encoding and One-Hot Encoding
label_encoders = label_encode_multiple_columns(X_train, X_test, X_val, label_columns)
X_train, X_test, X_val = one_hot_encode_multiple_columns(X_train, X_test, X_val, one_hot_columns)

In [823]:
print('X_train Shape:{}--y_train Shape:{}'.format(X_train.shape,y_train.shape))
print('X_val Shape:{}--y_val Shape:{}'.format(X_val.shape,y_val.shape))
print('X_test Shape:{}--y_test Shape:{}'.format(X_test.shape,y_test.shape))

X_train Shape:(52041, 95)--y_train Shape:(52041,)
X_val Shape:(13011, 95)--y_val Shape:(13011,)
X_test Shape:(16263, 95)--y_test Shape:(16263,)

In [824]:
X_train

,oam_activelogin_cnt,term_length,called_numcalls_cnt,curr_usage,deposit_onhand_amt,sap_productname,numweblog_cnt,OrderYear,OrderDay,OrderDayOfYear,IsWeekend,tos_flg_0,tos_flg_1,disconotice_flg_0,disconotice_flg_1,latefee_flg_0,latefee_flg_1,dwelling_type_cd_0,dwelling_type_cd_1,product_type_cd_0,product_type_cd_1,automatic_payment_flg_0,automatic_payment_flg_1,weblog_flg_0,weblog_flg_1,risk_level_0,risk_level_1,risk_level_2,ebill_enroll_flag_0,ebill_enroll_flag_1,called_flg_0,called_flg_1,oam_flg_0,oam_flg_1,disconnects_flg_0,disconnects_flg_1,load_profile_0,load_profile_1,load_profile_2,load_profile_3,load_profile_4,city_0,city_1,city_2,city_3,zipcode_0,zipcode_1,zipcode_2,zipcode_3,county_0,county_1,county_2,county_3,tdsp_0,tdsp_1,tdsp_2,tdsp_3,tdsp_4,dma_0,dma_1,dma_2,dma_3,ev_driver_0,ev_driver_1,segment_0,segment_1,segment_2,segment_3,segment_4,segment_5,segment_6,segment_7,segment_8,segment_9,segment_10,segment_11,OrderMonth_0,OrderMonth_1,OrderMonth_2,OrderMonth_3,OrderMonth_4,OrderMonth_5,OrderMonth_6,OrderMonth_7,OrderMonth_8,OrderMonth_9,OrderMonth_10,OrderMonth_11,OrderDayOfWeek_0,OrderDayOfWeek_1,OrderDayOfWeek_2,OrderDayOfWeek_3,OrderDayOfWeek_4,OrderDayOfWeek_5,OrderDayOfWeek_6
14152,0,12,0,0.0,0.0,1467,0,2017,24,83,0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
42976,0,12,1,0.0,0.0,389,0,2018,11,11,0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
78273,0,0,0,550.0,0.0,1318,0,2020,18,323,0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4847,0,16,0,2905.0,0.0,198,0,2017,13,13,0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9228,0,36,0,58.0,0.0,386,0,2017,28,28,1,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22237,0,0,0,1713.0,0.0,10152,0,2017,25,237,0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10987,0,12,1,0.0,0.0,279,0,2017,17,48,0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
55413,0,20,0,2441.0,0.0,1065,0,2018,22,356,1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
59588,0,0,0,462.0,0.0,1318,5,2019,4,4,0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3325,0,12,1,545.0,0.0,5749,0,2017,13,13,0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [827]:
X_train[num_cols]

,oam_activelogin_cnt,term_length,called_numcalls_cnt,curr_usage,deposit_onhand_amt,sap_productname,numweblog_cnt,OrderYear,OrderDay,OrderDayOfYear,IsWeekend
14152,0,12,0,0.0,0.0,1467,0,2017,24,83,0
42976,0,12,1,0.0,0.0,389,0,2018,11,11,0
78273,0,0,0,550.0,0.0,1318,0,2020,18,323,0
4847,0,16,0,2905.0,0.0,198,0,2017,13,13,0
9228,0,36,0,58.0,0.0,386,0,2017,28,28,1
...,...,...,...,...,...,...,...,...,...,...,...
22237,0,0,0,1713.0,0.0,10152,0,2017,25,237,0
10987,0,12,1,0.0,0.0,279,0,2017,17,48,0
55413,0,20,0,2441.0,0.0,1065,0,2018,22,356,1
59588,0,0,0,462.0,0.0,1318,5,2019,4,4,0
3325,0,12,1,545.0,0.0,5749,0,2017,13,13,0

## Numerical Preprocessing

In [828]:
# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit the scaler on the training data and transform it
X_train_scaled = scaler.fit_transform(X_train[num_cols])

# Transform the test and validation data using the same scaler
X_test_scaled = scaler.transform(X_test[num_cols])
X_val_scaled = scaler.transform(X_val[num_cols])

In [830]:
X_train_scaled =pd.DataFrame(X_train_scaled,columns=num_cols,index=X_train.index)
X_test_scaled =pd.DataFrame(X_test_scaled,columns=num_cols,index=X_test.index)
X_val_scaled =pd.DataFrame(X_val_scaled,columns=num_cols,index=X_val.index)

In [831]:
X_train_scaled

,oam_activelogin_cnt,term_length,called_numcalls_cnt,curr_usage,deposit_onhand_amt,sap_productname,numweblog_cnt,OrderYear,OrderDay,OrderDayOfYear,IsWeekend
14152,0.0,0.121212,0.000000,0.021776,0.0,0.144419,0.000000,0.000000,0.766667,0.225275,0.0
42976,0.0,0.121212,0.043478,0.021776,0.0,0.038223,0.000000,0.333333,0.333333,0.027473,0.0
78273,0.0,0.000000,0.000000,0.063799,0.0,0.129741,0.000000,1.000000,0.566667,0.884615,0.0
4847,0.0,0.161616,0.000000,0.243735,0.0,0.019407,0.000000,0.000000,0.400000,0.032967,0.0
9228,0.0,0.363636,0.000000,0.026207,0.0,0.037927,0.000000,0.000000,0.900000,0.074176,1.0
...,...,...,...,...,...,...,...,...,...,...,...
22237,0.0,0.000000,0.000000,0.152659,0.0,1.000000,0.000000,0.000000,0.800000,0.648352,0.0
10987,0.0,0.121212,0.043478,0.021776,0.0,0.027386,0.000000,0.000000,0.533333,0.129121,0.0
55413,0.0,0.202020,0.000000,0.208282,0.0,0.104817,0.000000,0.333333,0.700000,0.975275,1.0
59588,0.0,0.000000,0.000000,0.057075,0.0,0.129741,0.070423,0.666667,0.100000,0.008242,0.0
3325,0.0,0.121212,0.043478,0.063417,0.0,0.566250,0.000000,0.000000,0.400000,0.032967,0.0

In [832]:
X_train.drop(num_cols,axis=1,inplace=True)
X_test.drop(num_cols,axis=1,inplace=True)
X_val.drop(num_cols,axis=1,inplace=True)

In [833]:
X_train=X_train_scaled.join(X_train)
X_test=X_train_scaled.join(X_test)
X_val=X_train_scaled.join(X_val)

In [835]:
X_train.shape

(52041, 95)

In [836]:
X_train.head()

,oam_activelogin_cnt,term_length,called_numcalls_cnt,curr_usage,deposit_onhand_amt,sap_productname,numweblog_cnt,OrderYear,OrderDay,OrderDayOfYear,IsWeekend,tos_flg_0,tos_flg_1,disconotice_flg_0,disconotice_flg_1,latefee_flg_0,latefee_flg_1,dwelling_type_cd_0,dwelling_type_cd_1,product_type_cd_0,product_type_cd_1,automatic_payment_flg_0,automatic_payment_flg_1,weblog_flg_0,weblog_flg_1,risk_level_0,risk_level_1,risk_level_2,ebill_enroll_flag_0,ebill_enroll_flag_1,called_flg_0,called_flg_1,oam_flg_0,oam_flg_1,disconnects_flg_0,disconnects_flg_1,load_profile_0,load_profile_1,load_profile_2,load_profile_3,load_profile_4,city_0,city_1,city_2,city_3,zipcode_0,zipcode_1,zipcode_2,zipcode_3,county_0,county_1,county_2,county_3,tdsp_0,tdsp_1,tdsp_2,tdsp_3,tdsp_4,dma_0,dma_1,dma_2,dma_3,ev_driver_0,ev_driver_1,segment_0,segment_1,segment_2,segment_3,segment_4,segment_5,segment_6,segment_7,segment_8,segment_9,segment_10,segment_11,OrderMonth_0,OrderMonth_1,OrderMonth_2,OrderMonth_3,OrderMonth_4,OrderMonth_5,OrderMonth_6,OrderMonth_7,OrderMonth_8,OrderMonth_9,OrderMonth_10,OrderMonth_11,OrderDayOfWeek_0,OrderDayOfWeek_1,OrderDayOfWeek_2,OrderDayOfWeek_3,OrderDayOfWeek_4,OrderDayOfWeek_5,OrderDayOfWeek_6
14152,0.0,0.121212,0.000000,0.021776,0.0,0.144419,0.0,0.000000,0.766667,0.225275,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
42976,0.0,0.121212,0.043478,0.021776,0.0,0.038223,0.0,0.333333,0.333333,0.027473,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
78273,0.0,0.000000,0.000000,0.063799,0.0,0.129741,0.0,1.000000,0.566667,0.884615,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4847,0.0,0.161616,0.000000,0.243735,0.0,0.019407,0.0,0.000000,0.400000,0.032967,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9228,0.0,0.363636,0.000000,0.026207,0.0,0.037927,0.0,0.000000,0.900000,0.074176,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0